[package]
name = "rma"
version.workspace = true
edition.workspace = true

[dependencies]
three-d = { git = "https://github.com/trumank/three-d", features = ["egui-gui"] }
anyhow.workspace = true
serde = { version = "1.0.203", features = ["derive"] }
egui_extras = "0.32"
strum = { version = "0.26", features = ["derive"] }
log = "0.4"
futures = "0.3.30"
ordered-float = { version = "4.2.0", features = ["serde"] }
transform-gizmo-egui = "0.7.0"
enumset = "1.1.3"
asset_ser = { version = "0.1.0", path = "../../../../ue/asset_ser" }
uesave = { git = "https://github.com/trumank/uesave", version = "0.7.0" }
jmap = { git = "https://github.com/trumank/jmap", version = "0.1.0" }
