[package]
name = "rma"
version = "0.1.0"
edition = "2021"

[dependencies]
three-d = "0.16.0"
three-d-asset = { version = "0.6.0", features = ["pcd"] }
tokio = { version = "1.32.0", features = ["full"] }
unreal_asset.workspace = true
rma_lib = { path = "../rma_lib" }
anyhow.workspace = true
